name: lumiere
description: 'Application pour contrôler une lampe connecté'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  ionicons: ^0.2.2
  toggle_switch: ^2.3.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_launcher_icons: ^0.14.4
  flutter_time_picker_spinner: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0





flutter:
  uses-material-design: true
  assets:
    - images/

# App Icon :
flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"     # Optional (Android 8+)
  adaptive_icon_foreground: "images/app_icon.jpg"  # Optional (Android)